name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.name }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
            command: electron:win

          - name: Linux
            os: ubuntu-latest
            command: electron:linux

          - name: macOS
            os: macos-latest
            command: electron:mac

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Electron package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run ${{ matrix.command }} -- --publish never

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: release/


  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all build files
        uses: actions/download-artifact@v4
        with:
          path: release-files

      - name: Create Release and Upload Files
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-files/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}